### ISSUE TITLE
quick feedback

### ISSUE THREAD

**Issue by vladmandic** [BinaryQuantumSoul/sdnext-ui-ux#1]
overal, love it. still quite some things that need fixing...

generating creates a flicker during preview as scrollbars appear/dissapear

after running generate several times, generate button started to dissapear on me - it goes away when i click generate, but doesn't come back when generate is done:
![image](https://github.com/BinaryQuantumSoul/sdnext-ui-ux/assets/57876960/c7465b24-340b-46f3-b128-0424fec61cfd)

extra networks clicking on folder does not filter the view

remove buttons with links completely:
![image](https://github.com/BinaryQuantumSoul/sdnext-ui-ux/assets/57876960/cfd96473-6d40-4361-8076-c21b2f907b1b)

i don't see a point fo home button opening readme:
![image](https://github.com/BinaryQuantumSoul/sdnext-ui-ux/assets/57876960/96d5145f-2bcf-45f2-a329-a50f25db5fd3)

settings is broken - there is a main button on the left which just opens near-empty pane
![image](https://github.com/BinaryQuantumSoul/sdnext-ui-ux/assets/57876960/5105f279-086d-4464-8824-ddb818d59d5b)

and then there is button on the right which opens actual settings
![image](https://github.com/BinaryQuantumSoul/sdnext-ui-ux/assets/57876960/233137cb-0512-4994-951d-7045e2cb3397)

actually - i think this is an overall problem, not settings specific - if a tab has tab control inside it, main tab will be on the main pane, but subtabs appear on the right pane, probably not what we want.
perhaps instead of "dynamically" doing that, we can predetermine which sections go to main (left) and which to right.

also probably due to same root cause - not sure what this button is supposed to be, it just opens empty pane
![image](https://github.com/BinaryQuantumSoul/sdnext-ui-ux/assets/57876960/06a015a5-40da-4a6f-9fb3-407a7bd9a088)

**Comment by BinaryQuantumSoul** [comment]
Thanks for the feedback

> generating creates a flicker during preview as scrollbars appear/dissapear
> 
> after running generate several times, generate button started to dissapear on me - it goes away when i click generate, but doesn't come back when generate is done: ![image](https://private-user-images.githubusercontent.com/57876960/302681242-c7465b24-340b-46f3-b128-0424fec61cfd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyMzQ2MzEsIm5iZiI6MTcwNzIzNDMzMSwicGF0aCI6Ii81Nzg3Njk2MC8zMDI2ODEyNDItYzc0NjViMjQtMzQwYi00NmYzLWIxMjgtMDQyNGZlYzYxY2ZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA2VDE1NDUzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlZjAwNjhlZDU5NTYwZDA3NTMzZGExNzU2MzYzNDA4YWUzY2NkY2IzZGYzNzM1NjQ0NmYzYjM0MTE5ZmE3NjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Gkym-SZRBMzcPWTUW7i5Gfk47Hr3x9ozgCWqwjfh_pw)

Yes this one is on the trello, I haven't searched the cause yet, but it's probably a quick fix.

> extra networks clicking on folder does not filter the view

Didn't know, added it to the trello

> remove buttons with links completely: ![image](https://private-user-images.githubusercontent.com/57876960/302677903-cfd96473-6d40-4361-8076-c21b2f907b1b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyMzQ2MzEsIm5iZiI6MTcwNzIzNDMzMSwicGF0aCI6Ii81Nzg3Njk2MC8zMDI2Nzc5MDMtY2ZkOTY0NzMtNmQ0MC00MzYxLTgwNzYtYzIxYjJmOTA3YjFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA2VDE1NDUzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3NGM1ODc2MTgyZjQzZjRkYzM5MzIyMmVmMzRiMTg4MDMyNWJmZWY1ZTE1YWI1YWJhMWM4MjQzOTNkOGY3YTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Dr4IBqlAdirbnGcYfET9Y7PDGbjLvujqAuhictzTLDs)

Ok didn't know which one to leave. Do I keep the reload UI one ?

> i don't see a point fo home button opening readme: ![image](https://private-user-images.githubusercontent.com/57876960/302678154-96d5145f-2bcf-45f2-a329-a50f25db5fd3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyMzQ2MzEsIm5iZiI6MTcwNzIzNDMzMSwicGF0aCI6Ii81Nzg3Njk2MC8zMDI2NzgxNTQtOTZkNTE0NWYtMmJjZi00NWYyLWEzMjktYTUwZjI1ZGI1ZmQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA2VDE1NDUzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyOTEyYzNhNjRlN2Q1NTRmOTE5M2VlNTIzNmE3MmZiMDU4ODc5OWNjMDEzZDZkMWQ1NzkwZmNjMDhhNjA3MTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.a0jJONuKgYg5_z8pmYMv5Bw5kpe5nVLaEJhcbVPj05k)

Sure, but what should I put there then ? Initially it was information about Anapnoe's repo and sponsorship.

> settings is broken - there is a main button on the left which just opens near-empty pane ![image](https://private-user-images.githubusercontent.com/57876960/302678950-5105f279-086d-4464-8824-ddb818d59d5b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyMzQ2MzEsIm5iZiI6MTcwNzIzNDMzMSwicGF0aCI6Ii81Nzg3Njk2MC8zMDI2Nzg5NTAtNTEwNWYyNzktMDg2ZC00NDY0LTg4MjQtZGRiODE4ZDU5ZDViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA2VDE1NDUzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4ZDY1Yjg4YmIyZTVmZDZmNzVmZDY2OGZlMjZlNzE0M2JkY2QzNjc4NWVlZmIwZjQzZjBiY2RiOTc2ZDc2YmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FD9d5SrhRs6_yqH4ml56hvylEYoqrbLsUtsu8gYGoNc)
> 
> and then there is button on the right which opens actual settings ![image](https://private-user-images.githubusercontent.com/57876960/302679259-233137cb-0512-4994-951d-7045e2cb3397.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyMzQ2MzEsIm5iZiI6MTcwNzIzNDMzMSwicGF0aCI6Ii81Nzg3Njk2MC8zMDI2NzkyNTktMjMzMTM3Y2ItMDUxMi00OTk0LTk1MWQtNzA0NWUyY2IzMzk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA2VDE1NDUzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmNzk0YjBhMDliYzAxN2ZiYzcwOWEyNDVkMTljYjlkZDkxZjlmZmZiMGEwY2M0MTZiOTRlNDIzZWE0OTJiMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VhaqeVdhxcKirYp_pXYM_pleMppv3drcuidF1JlcQuQ)

Yes, I thought the right settings tab is useful so I left it there but we should hide the subtab in system tab then ? Or remove the quick gear icon ?

> actually - i think this is an overall problem, not settings specific - if a tab has tab control inside it, main tab will be on the main pane, but subtabs appear on the right pane, probably not what we want. perhaps instead of "dynamically" doing that, we can predetermine which sections go to main (left) and which to right.
> 
> also probably due to same root cause - not sure what this button is supposed to be, it just opens empty pane ![image](https://private-user-images.githubusercontent.com/57876960/302679466-06a015a5-40da-4a6f-9fb3-407a7bd9a088.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyMzQ2MzEsIm5iZiI6MTcwNzIzNDMzMSwicGF0aCI6Ii81Nzg3Njk2MC8zMDI2Nzk0NjYtMDZhMDE1YTUtNDBkYS00YTZmLTlmYjMtNDA3YTdiZDlhMDg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA2VDE1NDUzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmZWEyMjBmMTc1MGY2OTAwMDdhY2U2ZmZlNWU4M2Y2YjZkYTZiNWQyZTJmMDllMWNjMDNjMWFiNWYxNDc4YTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.trfVoSKwHN8RuStjhXLwgc-Ji4NdtGRFPApKvTyYT0c)

I don't see what you mean here, do you have other examples? Actually it's already predetermined, it's all templates that either teleport a whole tab or divs using their elem ids. The settings on the right teleports the subtab from system tab, that's why it's empty there. The empty tab is the control tab, I added it but it's empty since I haven't done the template yet (a1111 doesn't have control tab).

**Comment by vladmandic** [comment]
> Ok didn't know which one to leave. Do I keep the reload UI one ?

browsers have reload button already, no need.

> Sure, but what should I put there then ? Initially it was information about Anapnoe's repo and sponsorship.

probably nothing, just a non-clickable icon

>  Actually it's already predetermined, it's all templates that either teleport a whole tab or divs using their elem ids.

ok, so we should probably have better predefined list of whats teleported.
i like idea that settings are on the right, but right now its broken up to be settings headings in left and actual settings in the right.

**Comment by BinaryQuantumSoul** [comment]
> browsers have reload button already, no need.

> probably nothing, just a non-clickable icon

Ok x2

> ok, so we should probably have better predefined list of whats teleported.
> i like idea that settings are on the right, but right now its broken up to be settings headings in left and actual settings in the right.

I mean the right nav bar kinda is the list of what's teleported and the elements you see in the templates are the ones which are teleported, but I guess we could make a list. By the way, in the trello I have made a list of lacking elem_ids. Right now there is only one, but I may find other ones when doing the templates.

I'll hide the settings subtab and select the second one. Such that when using the theme the settings are in the gear right tab

**Comment by BinaryQuantumSoul** [comment]
I implemented all the opinionated UI fixes in latest. Still need to fix the two bugs but will track progress on trello
