### ISSUE TITLE
not working. just white page opened with some text...

### ISSUE THREAD

**Issue by SaymanNsk** [BinaryQuantumSoul/sdnext-ui-ux#3]
install SD.Next. Install this UI? reboot with cmd --theme modern and nothing....no page.

**Comment by SaymanNsk** [comment]
![image](https://github.com/BinaryQuantumSoul/sdnext-ui-ux/assets/21341336/1c289c93-c95b-459d-b2f5-8e6491f45270)

**Comment by BinaryQuantumSoul** [comment]
Fixed
