### ISSUE TITLE
General feedback

### ISSUE THREAD

**Issue by vladmandic** [BinaryQuantumSoul/sdnext-ui-ux#4]
Overall, massive progress and really like out-of-the-box look.

- bugs:
  - clicking on generated image does not open full screen viewer  
  - extra networks: clicking on folder still doesnt filter whats displayed in the list  
    (for any of the networks)

- left pane:
  - overal txt2img/img2img/control  
    - prompt/negative areas are huge  
      don't have a clear idea what to use that space for, but it feels like a waste of space  
    - default width of the left pane is half of the screen which is huge.  
      the fact that its resizable is great, but maybe set default to smaller value  
      imo around 500px looks much better  
    - settings sections have no headings which is maybe ok for most sections,  
      but correction section feels like "what is this" without heading.  
      maybe add section headings in general?  
  - txt2img:
    - width/height and batch size/count controls are verical instead of horizontal?
  - control:
    - control has extra control that txt2img/img2img dont - status text line
      can you add it?
    - action box (start/stop/skip) is misplaced, its above preview instead being on the top left like in txt2img or img2img sections  
    - if input/output/preview dont fit in the same row,  
      they overflow one-by-one so you end up small input/output and massive preview.  
      perhaps if they don't fit in the same row, then force all 3 to break into new row  
      so we don't end up 2 vs 1?  

- right pane:
  - sections no visal headings when displayed, perhaps add it?  
    e.g. when i click on models, and i see all of the items in the right pane, i'm not really sure where am i.
  - quick settings seem to be burried deep somehow, not really quick  
    perhaps combine quick settings + extra networks as default view?

**Comment by BinaryQuantumSoul** [comment]
Thanks for the feedback!

> bugs:
> 
>     * clicking on generated image does not open full screen viewer
> 
>     * extra networks: clicking on folder still doesnt filter whats displayed in the list
>       (for any of the networks)
Both are in the trello bug list. I did not take the time to look a them yet.


> * prompt/negative areas are huge
>       don't have a clear idea what to use that space for, but it feels like a waste of space

Indeed but I don't know either. One possibility could be most used params (sampler, batch or other).

> * default width of the left pane is half of the screen which is huge.
>       the fact that its resizable is great, but maybe set default to smaller value
>       imo around 500px looks much better

I will change default width then.


> * settings sections have no headings which is maybe ok for most sections,
>       but correction section feels like "what is this" without heading.
>       maybe add section headings in general?

It's in the trello todo list

> * width/height and batch size/count controls are vertical instead of horizontal?

It's not pretty ?



> * control has extra control that txt2img/img2img dont - status text line
>       can you add it?

Sure.



> * action box (start/stop/skip) is misplaced, its above preview instead being on the top left like in txt2img or img2img sections

It's also in the trello, but problem is that the point of rebuilding the control tab was to have params panel hiddeable, unlike the txt2img and img2img tabs. If I add the buttons there, we won;t be able to generate with the panel closed.
Where to put them ?



> * if input/output/preview dont fit in the same row,
>       they overflow one-by-one so you end up small input/output and massive preview.
>       perhaps if they don't fit in the same row, then force all 3 to break into new row
>       so we don't end up 2 vs 1?

I did not know what I should do in that case, so you want either a full row or full column ?

> * sections no visal headings when displayed, perhaps add it?
>       e.g. when i click on models, and i see all of the items in the right pane, i'm not really sure where am i.

So you want an heading in addition of the selected tab indicator ? I could add them.

> * quick settings seem to be burried deep somehow, not really quick
>       perhaps combine quick settings + extra networks as default view?

Why not, but that means extra networks will change size when adding quicksettings, Idk if that is a problem

**Comment by BinaryQuantumSoul** [comment]
> > width/height and batch size/count controls are vertical instead of horizontal?
> 
> imo, width/height is one row and batch size/count is one row

I will consider it but I also like how it is

> > I did not know what I should do in that case, so you want either a full row or full column ?
> 
> yes. either full row or full colum, never split.

Will do

> > So you want an heading in addition of the selected tab indicator ? I could add them.
> 
> yes. pretty much everywhere.

Will do

> > Why not, but that means extra networks will change size when adding quicksettings, Idk if that is a problem
> 
> i'm thinking for default right sidebar its quicksettings on top and extra networks below that.

Okay I'll try

> > start/skip/stop buttons
> 
> true, if they are on any section then that section must be visible - that is not control specific
> but...why not place them at the very top of the left (primary) side toolbar? then a separator and then we start with control/text/image buttons. then another separator so any extensions would be separated.
> 
> 

Interesting idea, I'll try too
