### ISSUE TITLE
General feedback

### ISSUE THREAD

**Issue by vladmandic** [BinaryQuantumSoul/sdnext-ui-ux#5]
## startup

we really dont need to print startup log in browser main view on startup
sdnext has splash screen, lets leave it as-is

## gallery

i like it!

- maybe move gallery from left panel to right panel, just below extra networks and before models?
- place search above folder list

## right panel

idea - can we make right panel expandable and not just collapsable?  
right now its either collapsed or set to ~1/3 of the screen width
but maybe i want to look at extra networks or gallery or settings at full width? so its full->1/3->collapsed

### extra networks

- search/filter is still broken
- sort is broken
- switch view type from icon to list is broken
- close button does not do anything in modern styling, maybe just hide it
- lora: overlay with tag words that is drawn on hover is normally below network itself and can grow much larger, here its cropped to size of the preview image  

### models -> update

this looks broken, but that's on me

### settings

expand settings section names a bit, right now its

### log

- move server log to top and client log to bottom
- add header to indicate what is server log and what is client log
- browser log is extremely verbose, if you need it, it needs to be behind some debug flag and not print-all by default  

### system

- benchmark: table view does not look that great  
- models & networks: this looks like json dump without json display  
  normally, this is `gr.JSON` component, but seems like modern styling breaks it

## left panel

i still think that generate action bar can fit as the top part of the left vertical toolbar :)

we still have a problem where prompt fields are massive  
thinking what is always absolutely needed, its the size - can we perhaps move size section to be above prompt?
and yes, control resizing section is a bit complex, but we can probably tweak it a bit so it fits there  

i like how img2img looks with prompt/negative/image in the left column and everything styled  
can similar be done with control? i think that might work pretty well for default?

txt2img and img2img have subsections set horizontally above prompt and control has it as vertical list
i understand this is because control left panel can be minimized and others cannot, but we need to get to uniform view

**Comment by vladmandic** [comment]
> We don't need to but the extension starts up after sdnext is fully started. So the splash screen is already gone.

we can modify when main js function `removeSplash()` is called so it works for both.
how about you remove your ui splash that shows loading logs and i'll handle this?

> For view type switch and lora overaly, I will need screenshots to understand.

screenshot showing lora tags:
![image](https://github.com/BinaryQuantumSoul/sdnext-ui-ux/assets/57876960/5fa4b835-c439-4f3b-b5fa-8296dc820899)

screenshot showing list mode view type:
![image](https://github.com/BinaryQuantumSoul/sdnext-ui-ux/assets/57876960/22d4a299-eb8b-4964-813a-868b1ac4fbef)

**Comment by vladmandic** [comment]
> It is already expandable, just like the left panel.

its manually expandable. i'm talking about this arrow that cycles through minimized or 1/3 size. and i'm suggesting to cycle between full-width, 1/3 size, minimized. right now there is no simple way to "maximize" right panel.

> I cannot move it to right panel since it has two inner panels, one for the browsing and one for the current image.

(gallery) - why not? i don't understand how number of inner panels would make it only work in left side and not right?

![image](https://github.com/BinaryQuantumSoul/sdnext-ui-ux/assets/57876960/39a982dd-d5f4-4ab3-bcd9-58ac663425e0)

> It can, but then the left toolbar will move when no generate buttons in some tabs. I was think of putting it always in top right above the result

(action bar) - i still like the idea of generate/skip/stop in left action bar. primary tabs all have it (txt2img, img2img, control, process). only one that doesn't is gallery and i'm suggesting to move gallery to right-panel anyhow. which would only leave extensions that create tabs - such as agent scheduler.

**Comment by vladmandic** [comment]
> We cannot move both resize and input image, and if we move resize in txt2img then it will be at a different place in img2img. I don't understand for control tab, it's not the same layout, here we have three columns where one of them is input. Will people really minimize control ? I need to have a better idea of what we want for control tab to not do/undo things many time

purely talking about txt2img and img2img, i think that size section need to be on the primary screen together with prompts.
not batch, not seed, not anything else, just size - as size and prompt matters to basic workflows.
and yes, size section for txt2img (simpler) and img2img (more complicated) are different, but i don't see how is that a problem?

and now expanding that to control tab, comes to same thing - size section should be together with prompt.
now, should control left tab be collapsible? honestly, its not that important. but if it already is there, better to have it as collapsible unless its an issue in which case collapsible feature can be removed.

oh, one more minor thing - control/output/preview - can you make them top-aligned? right now they are center aligned and it looks a bit weird.
![image](https://github.com/BinaryQuantumSoul/sdnext-ui-ux/assets/57876960/5cb368a0-6311-45bb-9329-df8dc8c4b2da)

and styling-wise, i don't think we need extra borders around inner control tab (darker gray in the screenshot below):
![image](https://github.com/BinaryQuantumSoul/sdnext-ui-ux/assets/57876960/1da567c5-a155-47ed-936c-1cf66a49fc90)

**Comment by BinaryQuantumSoul** [comment]
> how about you remove your ui splash that shows loading logs and i'll handle this?

OK

> screenshot showing lora tags:
> screenshot showing list mode view type:

Thanks

> > It is already expandable, just like the left panel.
> 
> its manually expandable. i'm talking about this arrow that cycles through minimized or 1/3 size. and i'm suggesting to cycle between full-width, 1/3 size, minimized. right now there is no simple way to "maximize" right panel.
> 
> ![image](https://private-user-images.githubusercontent.com/57876960/319315176-39a982dd-d5f4-4ab3-bcd9-58ac663425e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyMjA0NjEsIm5iZiI6MTcxMjIyMDE2MSwicGF0aCI6Ii81Nzg3Njk2MC8zMTkzMTUxNzYtMzlhOTgyZGQtZDVmNC00YWIzLWJjZDktNThhYzY2MzQyNWUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDA4NDI0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyMjUyNDhkMDgwZGQxOGI4ZTUyNTQ4YzAyNzQ0MzBhOTkxMjI5ZDc5MmE2NmM3OTg4MmMxMTUwMWJjMjFjZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BlFRmhqpd5YdRpK0J6JZa5tnDYQZLaizup0yF3kTD9k)
> 
> > I cannot move it to right panel since it has two inner panels, one for the browsing and one for the current image.
> 
> (gallery) - why not? i don't understand how number of inner panels would make it only work in left side and not right?
> 
> > It can, but then the left toolbar will move when no generate buttons in some tabs. I was think of putting it always in top right above the result
> 
> (action bar) - i still like the idea of generate/skip/stop in left action bar. primary tabs all have it (txt2img, img2img, control, process). only one that doesn't is gallery and i'm suggesting to move gallery to right-panel anyhow. which would only leave extensions that create tabs - such as agent scheduler.
> > 
> 
> purely talking about txt2img and img2img, i think that size section need to be on the primary screen together with prompts. not batch, not seed, not anything else, just size - as size and prompt matters to basic workflows. and yes, size section for txt2img (simpler) and img2img (more complicated) are different, but i don't see how is that a problem?
> 
> and now expanding that to control tab, comes to same thing - size section should be together with prompt. now, should control left tab be collapsible? honestly, its not that important. but if it already is there, better to have it as collapsible unless its an issue in which case collapsible feature can be removed.


Right now UI is separated in two parts with their own tabs. Most of the tabs on the left, including gallery, have two subparts and the right subpart is the center column. Right column is supposed to be for tools rather than workflows and they require smaller size. We couldn't place gallery there because we'd need four columns. I don't really see the point of maximizing right panel, we would need an extra click on the button to close the panel, and the right tabs aren't workflows on their own, we don't stay there for a long time. 
For the action bar, could you show on a screenshot where you'd place it? Right now I made control tab a bit unique from other tabs by having three columns in center column and having collapsible left panel, consequence is having vertical navbar rather than horizontal since it should be visible when collapsed and not having place for generate group. However I think generate group (action bar) was misplaced in the other tabs and that it would look better on top right of each of the center columns, just over the resulting image fro the generation. That way we wouldn't have the problem of navbar ad actionbar not fitting and being wrapped.  I don't think other tabs should be collapsible since they only have one center column. 
![image](https://github.com/BinaryQuantumSoul/sdnext-ui-ux/assets/19613657/d6488a39-9cc0-4144-9ab4-af7a2ad760cc)
![image](https://github.com/BinaryQuantumSoul/sdnext-ui-ux/assets/19613657/100eb374-2b07-49a8-a4e8-d6e79f11e0ae)
![image](https://github.com/BinaryQuantumSoul/sdnext-ui-ux/assets/19613657/2b3d7cf3-8688-4961-8131-d6f8badd3b42)


For the three control columns, I think if they are aligned top it looks even weirder because of empty space under them. I can try having the second column preview icon the same size as right column one. For the left column input box, I am open to suggestions, though removing the border here will look extra weird
![image](https://github.com/BinaryQuantumSoul/sdnext-ui-ux/assets/19613657/e79c3f85-4c28-4181-9df8-eddbd6093a12)


For the txt2img, img2img, control params resize, I can move it under prompts, my question was about where do I place input image in the case of img2img, because it's either resize or input image, I think.

**Comment by vladmandic** [comment]
re: generate/skip/stop/enqueue 

i'm thinking something simple like this:
![image](https://github.com/BinaryQuantumSoul/sdnext-ui-ux/assets/57876960/ada92b3c-75e5-4454-85c4-5868957188cb)

just better icons:
- play icon=generate
- skip-forward icon=skip
- pause icon=pause
- stop icon=stop
- record icon=enqueue

and nothing else.

which leaves out: restore, clear plus everything from right-click context menu that we still need to think where to place (right now you have generate forever next to generate, but nothing else from context menu).

contextually, restore and clear would ideally be placed right next to styles refresh button - if that is possible (yes, they come from different parts of ui, but they really do fit there contextually)

for now, right-click context menu can stay as that.

**Comment by vladmandic** [comment]
> For the txt2img, img2img, control params resize, I can move it under prompts, my question was about where do I place input image in the case of img2img, because it's either resize or input image, I think.

its not either, its both:
- txt2img has size since you cannot generate without it
- img2img has resize since if you don't specify anything, it will use image size. but you can (and often do) use resize.
  resize can be fixed (resize-to-pixels) or scale (resize-to-2x-of-input-image). and if you're resizing, you need to choose method.

so all-in-all, resize in img2img is more complex than just size in txt2img but its equally important and often used.
and in control its even more complex, but also nearly always used. and if something is nearly always used, then it should be on first-screen, together with prompt. regarding placement, i'm just not sure if it should be above or below prompt.

**Comment by vladmandic** [comment]
re: control

> For the three control columns, I think if they are aligned top it looks even weirder because of empty space under them

i mean top-aligned, but fill entire space, not have small controls placed in the center of tab.
example screenshot:

![image](https://github.com/BinaryQuantumSoul/sdnext-ui-ux/assets/57876960/1b126371-a421-4594-9cf9-798cc099b084)

**Comment by vladmandic** [comment]
re: gallery

> Right column is supposed to be for tools rather than workflows and they require smaller size. We couldn't place gallery there because we'd need four columns. I don't really see the point of maximizing right panel, we would need an extra click on the button to close the panel, and the right tabs aren't workflows on their own, we don't stay there for a long time.

but that's exactly why i'm proposing to move gallery there - its a tool, not a workflow.

right now you have expand-arrow if its minimized and collapse-arrow if its expanded to ~1/3.

what i'm suggesting is 3 views:
- minimized shows expand-arrow and works as-is
- expanded to ~1/3 shows BOTH expand-arrow and collapse-arrow
  collapse arrow works as-is, but newly added expand arrow basically places right pane into full-width mode
- full-width: shows collapse-arrow which goes back to ~1/3 expanded view

and that full-width mode would be very useful not just for gallery - for example, just looking at settings on 1024px width right now looks really bad. to make it useful, i need to resize panel width (btw, great that we have that!), do whatever i need and then resize it back.

**Comment by vladmandic** [comment]
off-topic, regarding your icon svg's - check out nerd-fonts - there is really good stuff built-in and its easy to use,  
i don't think we even need svgs for something that's a simple play/pause/stop/fast-forward buttons.

**Comment by BinaryQuantumSoul** [comment]
Okay so I make two columns template for img2img and just like control tab it will turn to subtabs when too narrow. I will put all generate buttons in top right for it to be consistent.

I already put resize in prompt tab for all tabs so check out how it looks. I also made console splash screen optional. But without your loading splash screen it looks odd, so looking for you to put it.

For the simplification of txt2img, gallery and overall experience we'll see feedback after release.

For the nerdfont I am not sure, I like to handle everything the same way, so I'd need to find new icons for all current icons. But it's possible

So new templates are the priority then I can checkout the extra networks bugs

**Comment by vladmandic** [comment]
started looking at splash screen, but then got distracted and completely refactored how js code deals with callbacks.
(as i've noticed how many junk callbacks are triggered)

anyhow...now we have about 90% less irrelevant callbacks and what remains works like a charm.
plus entire startup sequence is now in `startup.js`
and yes, it checks if modern ui is active and waits for it before removing splash.
and entire browser loading is now about 20% faster at least.

on your side:
- remove splash showing of log, not needed anymore
- replace final section `document.addEventListener("DOMContentLoaded", () => { ...` with a single line:
`onUiReady(mainUiUx);`

i also took a look at uiux js code, one thing that will need to be refactored in the future is entire `movePortal` functionality. right now it works fine, but the problem is that for every moved element, browser needs to do a full reflow and repaint and that adds more than few seconds to startup.

not sure what's the best way: doing entire update in shadow-dom first and then swapping it? using html fragments? cheap-trick with will-change? something else...

**Comment by BinaryQuantumSoul** [comment]
Discussion on optimisation continues in #6
